<?php
/**
 * @file Update hooks and unistall.
 */

/**
 * Implements hook_uninstall.
 */
function componentize_unistall() {
  // Remove admin configurations.
  global $conf;
  foreach($conf as $key => $value) {
    if (0 === strpos($key, 'componentize_')) {
      variable_del($conf[$key]);
    }
  }

  // Delete all stored components.
  foreach (componentize_list() as $component) {
    $component->delete();
  }
}
