<?php
/**
 * @file Update hooks and unistall.
 */

/**
 * Implements hook_uninstall.
 */
function componentize_unistall() {
  foreach (array(
      'components_directory',
      'components_list',
      'components_blocks',
      'components_cache',
    ) as $var) {
    variable_del($var);
  }

  // Delete all stored component variables, if any.
  foreach (componentize_list() as $component) {
    $component->delete();
  }
}
