<?php
/**
 * @file Render content fieldgroups through a component.
 */

use Componentize\ComponentFactory;


/**
 * Implements hook_ctools_plugin_api().
 */
function componentize_fieldgroup_ctools_plugin_api($module, $api) {
  if ($module == 'field_group' && $api == 'field_group') {
    return array('version' => 1);
  }
}


/**
 * Implements hook_field_group_formatter_info().
 *
 * @todo Avoid showing up in form admin.
 */
function componentize_fieldgroup_field_group_formatter_info() {
  return array(
    'display' => array(
      'component_fieldgroup' => array(
        'label' => t('Component'),
        'descripton' => t("This fieldgroup renders the inner content using the selected Component's structure"),
        'instance_settings' => array(
          'component' => '',
          'modifiers' => '',
        ),
      ),
    ),
  );
}


/**
 * Implements hook_theme().
 */
function componentize_fieldgroup_theme() {
  return array(
    'component_fieldgroup' => array(
      'render element' => 'element',
    ),
  );
}


/**
 * Implements hook_field_formatter_settings_summary_alter().
 *
 * Display field mapping settings to admins.
 */
function componentize_fieldgroup_field_formatter_settings_summary_alter(&$summary, $context) {
  $field_display_mode = $context['instance']['display'][$context['view_mode']];
  $hidden = ($field_display_mode['type'] === 'hidden');

  // We know about this type of field.
  if (!$hidden && in_array($context['field']['type'], array_keys(componentize_fields_types())) &&
      isset($field_display_mode['settings']['componentize_fields_variable_name'])) {

    $view_mode_settings = _componentize_fields_get_view_mode_display_settings(
      $context['instance']['entity_type'], $context['instance']['bundle'], $context['view_mode']
    );

    // Ensure not entity view mode component.
    if (!isset($view_mode_settings->component) || empty($view_mode_settings->component)) {
      _componentize_fields_generate_summary($summary, $field_display_mode['settings']);
    }
  }
}


/**
 * Implements hook_field_formatter_settings_form_alter().
 *
 * Add settings to fields within component fieldgroups.
 *
 * @param array $settings_form
 * @param array $context
 */
function componentize_fieldgroup_field_formatter_settings_form_alter(&$settings_form, $context) {
  $field_display_mode = $context['instance']['display'][$context['view_mode']];

  if ($field_display_mode['type'] !== 'hidden') {
    $group_settings = componentize_fieldgroup_get_group_settings($context);

    // Use configured compontent.
    if (isset($group_settings['component'])) {
      $component = ComponentFactory::create($group_settings['component']);
      // Choose variables.
      _componentize_fields_generate_variable_form(
        $settings_form, $component, $field_display_mode['settings']
      );
    }
  }
}


/**
 * Obtain group settings from field via form data.  Handles multiple-contexts.
 *
 * @todo Find if this field is in the group from the _summary_alter() context.
 *
 * @param array $context
 * @return array
 */
function componentize_fieldgroup_get_group_settings($context) {
  $field_name = $context['instance']['field_name'];

  if (isset($context['form_state'])) {
    // @todo More carefully confirm there is a fieldgroup set.
    $parent_group = $context['form_state']['input']['fields'][$field_name]['parent'];
    return $context['form_state']['field_group'][$parent_group]->format_settings['instance_settings'];
  }
  else {
    // $instance = field_info_instance(
    //   $context['instance']['entity_type'], $field_name, $context['instance']['bundle']
    // );
    return FALSE;
  }
}


/**
 * Get relevant field data in display mode for rendering component.
 *
 * @param array $element
 * @return array
 */
function _componentize_fieldgroup_get_fields($element, $group) {
  $entity_type = $group->entity_type;
  $entity = FALSE;
  $vars = array();

  foreach ($group->children as $name) {
    $field_info = field_info_instance(
      $element[$name]['#entity_type'], $name, $element[$name]['#bundle']
    );

    $settings = _componentize_fields_get_field_settings(
      $field_info, $element[$name]['#view_mode']
    );

    // Only include componentized fields.
    if ($settings) {
      // Prepare data for rendering.
      $entity = $entity ?: $element[$name]['#object'];
      $items = field_get_items($entity_type, $entity, $name);

      // Prepare field for template.
      $template_var = $settings['componentize_fields_variable_name'];
      $vars[$template_var . '_label'] = $element[$name]['#title'];
      $vars[$template_var] = componentize_fields_render_field(
        $name, $entity_type, $entity, $element[$name]['#items'], $settings
      );
    }
  }

  return $vars;
}


/**
 * Implements field_group_pre_render_<format-type>.
 * Format: component_fieldgroup
 *
 * @param array &$element
 * @param array $group
 * @param array &$form
 */
function field_group_pre_render_component_fieldgroup(&$element, $group, &$form) {
  // @todo May want to access the label position within the template.
  // $element['#label_display']

  // Add necessary items to variables within theme function.
  $element += array(
    '#type' => 'component_fieldgroup',
    '#theme' => 'component_fieldgroup',
    '#title' => t($group->label),
    '#description' => $group->description,
    '#parents' => array($group->parent_name),
    '#componentize_fields' => _componentize_fieldgroup_get_fields($element, $group),
    '#componentize_settings' => $group->format_settings['instance_settings'],
    '#view_mode' => $group->mode,
  );
}


/**
 * Returns HTML for a component fieldgroups.
 *
 * @param array $variables
 *
 * @return string
 */
function theme_component_fieldgroup($variables) {
  $element = $variables['element'];
  // @todo Deal with multiple forms on page issue with modifier saving.
  $modifier = isset($element['#componentize_settings']['modifier']) ?
      $element['#componentize_settings']['modifier'] : FALSE;

  // Pass data through template.
  $component = ComponentFactory::create($element['#componentize_settings']['component']);

  // Make modifier available in the template.
  if ($modifier) {
    $component->setModifier($modifier);
  }

  return $component->render($element['#componentize_fields']);
}
